### ISSUE TITLE
Sync version for yolov4?

### ISSUE THREAD

**Issue by maxjundo** [TNTWEN/OpenVINO-YOLOV4#16]
Hi!

Your code works great, thanks for this repository. Is there a synchronous version for Yolov4? I tried to run the yolov4 converted network on a typical openvino sync script "object_detection_sample_ssd.py" script works, but bounding boxes draws in the wrong positions.

**Comment by TNTWEN** [comment]
Hello！Thanks for your trying
https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/7947ce4ca4e6602947484d98585abb013a422ece/object_detection_demo_yolov4_async.py#L454

I think the TAB key is used to switch between synchronous and asynchronous modes
And I think YOLO's model should not be able to run on SSD demo.Does YOLOv3 support such use?
