### ISSUE TITLE
FPS of YoloV4 tiny is slower than Yolo3 tiny

### ISSUE THREAD

**Issue by at1993** [TNTWEN/OpenVINO-YOLOV4#17]
@TNTWEN , thanks for the great work. I was able to convert and run the yolov4 tiny using the object_detection_demo_yolov3_async demo program. I've noticed that this new model is 10fps slower than yolov3 tiny. Then I realized the model is using data type FP32 vs FP16 in yolov3 tiny ( file size: 23MB vs 16.8MB). Is there a way to convert it to FP16? Thanks.

**Comment by TNTWEN** [comment]
Hello! @at1993 
Thanks for your trying!
https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/10, 

10、FP32 ,FP16
The default precision is FP32,if you want to use FP16 ,add --data_type FP16 when you run mo.py

python "C:\Program Files (x86)\IntelSWTools\openvino_2020.4.287\deployment_tools\model_optimizer\mo.py" --input_model frozen_darknet_yolov4_model.pb --transformations_config yolo_v4_tiny.json --batch 1 --reverse_input_channels --data_type FP16

**Comment by TNTWEN** [comment]
https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/5
For intel GPU,FP16 is more suitable than FP32

**Comment by at1993** [comment]
Thank you. Yes I agree that FP16 is better on intel GPU. 
I did try the conversion today with --data_type PF16 however, file size did not changed compared to PF32 (should be half the size right?). I thought maybe I've overlooked something.

**Comment by at1993** [comment]
@TNTWEN , I did a quick test, there's no difference in fps .
