### ISSUE TITLE
ValueError: cannot reshape array of size 251802 into shape (512,512,3,3)

### ISSUE THREAD

**Issue by zhubinsheng** [TNTWEN/OpenVINO-YOLOV4#19]
python3 convert_weights_pb.py --class_names coco_pf.names --weights_file yolov4-tiny-_final.weights --data_format NHWC --tiny
Hello, when I use the above command, I give the following error report
ValueError: cannot reshape array of size 251802 into shape (512,512,3,3)
How to solve this problem, thank you very much

**Comment by TNTWEN** [comment]
你好！ 可能会是以下问题，你排查一下
1：训练时的.weights 模型的输入图片大小是多少 需要与convert_weights_pb.py里的输入匹配  https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/10  第三和第四点
2：确保.names文件类别数量和训练模型一致

**Comment by sparkie2640** [comment]
Hello there! It may be the following problems, please check
1: What is the input image size of the .weights model during training? It needs to match the input in convert_weights_pb.py #10 The third and fourth points
2: Ensure that the number of .names file categories is consistent with the training model
---

I get the same error when trying to convert a custom yolov4-tiny model. Size is 416x416 and number of classes is 6, with the cfg file edited to fix the filters to be 33.

**Comment by TNTWEN** [comment]
@zhubinsheng @sparkie2640 
Have you solved the problem?
You can share your. cfg and. names files here

**Comment by TNTWEN** [comment]
And how you train your model is also important. Many repos don't build models according to darknet . cfg, which also causes the. weights file to conflict with the this repos. You could use https://github.com/AlexeyAB/darknet  or  https://github.com/ultralytics/yolov3 to train your model!

**Comment by sparkie2640** [comment]
Names File 20201101_v4.names:
`Flower
Disease
Stalk
Ground
Tractor
Wheel`

CFG File 20201101_v4.cfg:
`[net]
#Training
batch=64
subdivisions=8
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.00261
burn_in=200
max_batches=12000
policy=steps
steps=9600,10800
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize = 1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize = 1
filters=32
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize = 1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize = 1
filters=128
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

##################################

[convolutional]
batch_normalize = 1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize = 1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size = 1
stride=1
pad=1
filters=33
activation=linear
[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=6
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms = 0.6

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=33
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride = 2

[route]
layers = -1, 23

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size = 1
stride=1
pad=1
filters=33
activation=linear

[yolo]
mask = 1,2,3
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=6
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms = 0.6`

Trained on the latest pull of AlexeyAB's fork of darknet
darknet detector train 20201101_v4.data 20201101_v4-train.cfg  yolov4-tiny.conv.29 -dont_show -mjpeg_port 8090

I've compared the cfg file to the stock yolov4-tiny from Alexey's repo. With the exception of burn-in, batches, steps, classes, and filters the cfg file is identical, and correct. I am able to do yolov3 no problem. 

I can also provide the weights file if you'd like.

**Comment by sparkie2640** [comment]
I believe I found the issue in the cfg file during training. One of the convolutional layers was set to 33 when it should be 128. Retraining now.

**Comment by zhubinsheng** [comment]
我使用你提供的yolov4-tiny.weights文件可以转化成功，而且可以在任何条件转化成功，比如我修改成我自己的ｃｏｃｏ．name 或者是我自己的ｃfg文件或者是在这里面修改成inputs = tf.placeholder(tf.float32, [None, 1920, 1080, 3], "inputs")，都是可以转化成功．
这很奇怪，我只是一个新手，但是实验让我认为修改参数不是关键的原因，根本的决定因素是训练模型使用的参数

**Comment by TNTWEN** [comment]
因为没有全连接层，Yolo模型是不限制输入大小的，并且支持多尺度训练，此项目中输入大小和训练时大小匹配只会影响你的检测效果。在使用你自己的数据集训练时，模型结构只需要也只能修改yolo层的类别数量和yolo层前的那个卷积通道。darknet中训练模型即使改错了cfg文件也能训练，但tensorflow是静态图，如果训练错误就会导致你遇到的情况。在本项目中根据names文件自动识别你的类别数，所以一定要使用正确的names文件。

**Comment by TNTWEN** [comment]
类别数量影响yolo层前的卷积层通道数量，通道数量决定了模型参数量，我没有尝试过在转换为pb模型时候用错误的类别数，我觉得如果你设大于80个类别，weights文件中的参数就会不够用，就会报错。如果你是把类别改少了，模型参数够用，也不会报错，只不过错误地转换了模型而已。你可以尝试一下

**Comment by sparkie2640** [comment]
Yes, you are correct on all counts. The training was done improperly, with one of the convolutional layers changed from 128 to 33, so when it was converted it was expecting more data in the array which was not there. Hence the shape error.

**Comment by TNTWEN** [comment]
> Yes, you are correct on all counts. The training was done improperly, with one of the convolutional layers changed from 128 to 33, so when it was converted it was expecting more data in the array which was not there. Hence the shape error.

Yes！For yolov3 and yolov4 (not tiny version) I also made a tool that automatically parses the .cfg file to generate the conversion code, also welcome to try https://github.com/TNTWEN/OpenVINO-YOLO-Automatic-Generation
This month I will share how to optimize the full version of the YOLOv3/v4 model in OpenVINO for deployment at the edge
