### ISSUE TITLE
Can it be used in NSC2?

### ISSUE THREAD

**Issue by dssdyx** [TNTWEN/OpenVINO-YOLOV4#21]
I train yolov4 model and convert it to openvino. It can work well in CPU but cannot be loaded in NSC2. Does anyone have a try like this?

**Comment by silasalves** [comment]
I did not encounter this problem when running it with NCS2. I used [OpenVino Toolkit 2021.1 docker image](https://hub.docker.com/r/openvino/ubuntu18_dev) and followed the instructions to convert the yolov4.weights available [darknet repository](https://github.com/AlexeyAB/darknet/). I did not try to convert a custom trained network.

**Comment by dssdyx** [comment]
> I did not encounter this problem when running it with NCS2. I used [OpenVino Toolkit 2021.1 docker image](https://hub.docker.com/r/openvino/ubuntu18_dev) and followed the instructions to convert the yolov4.weights available [darknet repository](https://github.com/AlexeyAB/darknet/). I did not try to convert a custom trained network.
What size of your yolov4 .xml model is ? My xml model size is very large, about 250MB.

**Comment by dssdyx** [comment]
> I did not encounter this problem when running it with NCS2. I used [OpenVino Toolkit 2021.1 docker image](https://hub.docker.com/r/openvino/ubuntu18_dev) and followed the instructions to convert the yolov4.weights available [darknet repository](https://github.com/AlexeyAB/darknet/). I did not try to convert a custom trained network.

What size of your yolov4 .xml model is ? My xml model size is very large, about 250MB.

**Comment by silasalves** [comment]
My `frozen_darknet_yolov4_model.pb` has 258 MB and my `frozen_darknet_yolov4_model.xml` has 328 kB.

I am assuming that by "XML" you actually meant the `.pb` file. If your XML file has 250 MB, then something is likely wrong. The XML contains the architecture structure (i.e. what are the layers and how they connect to each other), not the weights, so it shouldn't be large.

Did you try converting the official `yolov4.weights` available from darknet repository, or only your custom trained network?

**Comment by dssdyx** [comment]
> My `frozen_darknet_yolov4_model.pb` has 258 MB and my `frozen_darknet_yolov4_model.xml` has 328 kB.
> 
> I am assuming that by "XML" you actually meant the `.pb` file. If your XML file has 250 MB, then something is likely wrong. The XML contains the architecture structure (i.e. what are the layers and how they connect to each other), not the weights, so it shouldn't be large.
> 
> Did you try converting the official `yolov4.weights` available from darknet repository, or only your custom trained network?

Thanks for your reply. I will try it.
