### ISSUE TITLE
yolov3 tiny prn with ncs2

### ISSUE THREAD

**Issue by BB142** [TNTWEN/OpenVINO-YOLOV4#23]
Hey, awesome work.
yolov4 tiny works fine on ncs2.

i tried to deploy yolov3 tiny prn on ncs2 and get split.1 error.
So i saw your post on openvino github but i don't understund how you solved the problem.

I don't know how and where to change split operation to slice operation.

When i use the benchmarkapp my model works fine. When i inference an image i get now 3 outputs [(1,18,19,19),(1,18,38,38),(1,128,38,38) for the split part) instead of 2 [(1,128,19,19),(1,128,38,38).
Typically i pass these outputs to parse_yolo_region with yoloparams. But what to do with these new outputs?

Any tips on how to change split to slice or how to work with the new outputs?
I would really appreciate your help

**Comment by TNTWEN** [comment]
@BB142  Hello
This repos only supports yolov4 series. And OpenVINO has already supported yolov3 and yolov3tiny
You can refer to this link：
https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html

And you will use this repos：
https://github.com/mystic123/tensorflow-yolo-v3

**Comment by TNTWEN** [comment]
For yolov3-tiny,you won't have this“split” problem. Because only yolov4-tiny uses this split operation.

Thanks for your using!  ^-^

**Comment by BB142** [comment]
Thank you for your fast response and sorry for posting a yolov3 issue in your yolov4 repo. I thought you were talking about this:
https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3-tiny-prn.cfg
model in your issue on openvino because i get the exact same split.1 error through the shortcut operations.
I converted it with this repo:
https://github.com/rdkannao/tensorflow-yolo-v3
because it supports yolo tiny with partial residual network
