### ISSUE TITLE
Could this project convert customized YOLOV4 model

### ISSUE THREAD

**Issue by chunhsieh53** [TNTWEN/OpenVINO-YOLOV4#26]
I have trained customized YOLOV4 model, which has only 4 classes.
Could I use the project to convert it to OPENVINO? and how to do.

**Comment by TNTWEN** [comment]
Hello @chunhsieh53 

- when you run `python convert_weights_pb.py --class_names cfg/coco.names --weights_file yolov4.weights --data_format NHWC
`      replace coco.names with your own class file

- when you run `python "C:\Program Files (x86)\IntelSWTools\openvino_2020.4.287\deployment_tools\model_optimizer\mo.py" --input_model frozen_darknet_yolov4_model.pb --transformations_config yolov4.json --batch 1 --reverse_input_channels
` change “80” to “4” in this line  https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/6679af7e4cfca58e6aca832d983d04e3e1893a1f/yolov4.json#L6

**Comment by chunhsieh53** [comment]
Thanks. It works.
