### ISSUE TITLE
AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'

### ISSUE THREAD

**Issue by stoneWeb** [TNTWEN/OpenVINO-YOLOV4#29]
`object_detection_demo_yolov3_async.py ` this file does not support the latest version of openvino, can you update it?
I think the official website uses nGraph instead of openvino.inference_engine.ie_api.IENetwork.layers.

```
 File "object_detection_demo_yolov3_async.py", line 233, in get_objects                                
 out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'
```

**Comment by TNTWEN** [comment]
Do you use this repo's object_detection_demo_yolov3_async.py ？
You should use YOLOv3 Python or C++ demo corresponds to the version of openvino you download.  You can find them in your openvino download directory.

As long as the official demo still supports https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html ， this YOLOv4 repo works.

We also find openvino 2021.1 2021.2's GPU bug: we talk about it here:https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/18
We have also fed back the problem to OpenVINO : https://github.com/openvinotoolkit/openvino/issues/2925

**Comment by vincentzxll** [comment]
> `object_detection_demo_yolov3_async.py ` this file does not support the latest version of openvino, can you update it?
> I think the official website uses nGraph instead of openvino.inference_engine.ie_api.IENetwork.layers.
> 
> ```
>  File "object_detection_demo_yolov3_async.py", line 233, in get_objects                                
>  out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
> AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'
> ```
Hi 
I think you could refer to the link of the comment:
https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/openvino-inference-engine-ie-api-IENetwork-object-has-no/m-p/1247181#M22392
The writer has already give one correction for it:
https://gist.github.com/AdamGerzsai/d2b596729e127e449cbf2e6613411dd0
I solve the similar issue with yours refer to the above files.
Hope it will help.
FYI.

**Comment by TNTWEN** [comment]
@vincentzxll @stoneWeb 
Just use YOLOV3  C++ and Python inference  demo provided by the OpenVINO you download.
We have tested OpenVINO2021.1 and OpenVINO2021.2. Everything is OK.

**Comment by stoneWeb** [comment]
Thanks all, solved!

**Comment by Nitin286roxs** [comment]
Hi, 
Did someone try to extract intermediate layer weight?
in the old release, I was able to get weight from the network just using this `dist_layer_wt = net.layers["dist"].weights["weights"]`
