### ISSUE TITLE
How to run it with GPU

### ISSUE THREAD

**Issue by freedom9393** [TNTWEN/OpenVINO-YOLOV4#30]
You showed this:

```
#windows  default OpenVINO path

python convert_weights_pb.py --class_names cfg/coco.names --weights_file yolov4.weights --data_format NHWC

"C:\Program Files (x86)\IntelSWTools\openvino\bin\setupvars.bat"

python "C:\Program Files (x86)\IntelSWTools\openvino_2020.4.287\deployment_tools\model_optimizer\mo.py" --input_model frozen_darknet_yolov4_model.pb --transformations_config yolov4.json --batch 1 --reverse_input_channels

python object_detection_demo_yolov3_async.py -i cam -m frozen_darknet_yolov4_model.xml  -d CPU
```

But, how should I modify these code for running (testing) on GPU?

**Comment by TNTWEN** [comment]
python object_detection_demo_yolov3_async.py -i cam -m frozen_darknet_yolov4_model.xml  -d GPU

**Comment by freedom9393** [comment]
Nothing to change in this line?:

`python convert_weights_pb.py --class_names cfg/coco.names --weights_file yolov4.weights --data_format NHWC`

**Comment by TNTWEN** [comment]
> Nothing to change in this line?:
> 
> `python convert_weights_pb.py --class_names cfg/coco.names --weights_file yolov4.weights --data_format NHWC`

 It needs to be reminded that：
GPU needs FP16：https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/10 （Point 10）
For yolov4  only OpenVINO2020.4 supports GPU:https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/10 （Point11）
Yolov4-tiny and yolov4-tiny-3l support OpenVINO2020.4 or newer and all inference devices

**Comment by freedom9393** [comment]
@TNTWEN, thanks! And I just tried to run it with GPU and it worked. I'm using OpenVINO2021.2.185. Maybe they fixed the bug?

**Comment by TNTWEN** [comment]
@freedom9393 
OpenVINO2021.2.185+GPU+FP16+YOLOv4  could detect objects normally？
Are you sure FP16 is used?

**Comment by freedom9393** [comment]
Yes

**Comment by TNTWEN** [comment]
Thanks! We will verify it!

**Comment by TNTWEN** [comment]
@freedom9393 
In my test ,the bug still seems to exist
