### ISSUE TITLE
AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'

### ISSUE THREAD

**Issue by freedom9393** [TNTWEN/OpenVINO-YOLOV4#31]
When I run following line of code:

`python object_detection_demo_yolov3_async.py -i cam -m frozen_darknet_yolov4_model.xml  -d CPU`

I'm getting this error:

> AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'

What does that mean and how to solve it?

**Comment by TNTWEN** [comment]
@freedom9393 
README：
![image](https://user-images.githubusercontent.com/49018311/109612911-65871200-7b6b-11eb-9734-f8ab233b5edf.png)

AND

https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/29

**Comment by TNTWEN** [comment]
https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo

**Comment by freedom9393** [comment]
@TNTWEN, so you updated demo (py) files ??

**Comment by TNTWEN** [comment]
Yes! 
I updated python inference demo for different OpenVINO version.

And OpenVINO already provides C++ inference demo.For windows,You could find it here:`C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\demos\multi_channel\object_detection_demo_yolov3`. I have tested it,it works well.
