### ISSUE TITLE
No module named 'ngraph'

### ISSUE THREAD

**Issue by JackieNJUST** [TNTWEN/OpenVINO-YOLOV4#34]
Hi, I run the code on raspberry 4B, but reported error.
Traceback (most recent call last):
  File "yolov4-tiny-detection.py", line 15, in <module>
    import ngraph as ng
ModuleNotFoundError: No module named 'ngraph'

**Comment by TNTWEN** [comment]
@JackieNJUST 
Hello!
Where did you get  "yolov4-tiny-detection.py"？
OpenVINO start to use "import ngraph as ng" from OpenVINO 2021.2,And i provided the inference demo here : https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/master/pythondemo/2021.2/object_detection_demo_yolov3_async.py

If your OpenVINO version is 2020.4 or 2021.1 you should use: https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2020.4   and  https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.1

**Comment by JackieNJUST** [comment]
> @JackieNJUST
> Hello!
> Where did you get "yolov4-tiny-detection.py"？
> OpenVINO start to use "import ngraph as ng" from OpenVINO 2021.2,And i provided the inference demo here : https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/master/pythondemo/2021.2/object_detection_demo_yolov3_async.py
> 
> If your OpenVINO version is 2020.4 or 2021.1 you should use: https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2020.4 and https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.1

**Comment by JackieNJUST** [comment]
My OpenVINO version is 2021.2.  “yolov4-tiny-detection.py” this file is copy from https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/master/pythondemo/2021.2/object_detection_demo_yolov3_async.py.
