### ISSUE TITLE
run object_detection_demo_yolov4_async.py

### ISSUE THREAD

**Issue by 17695996717** [TNTWEN/OpenVINO-YOLOV4#36]
when i run inference code,i get this error,what is it?how can i solve it? thank you~

[ INFO ] Creating Inference Engine...
[ INFO ] Loading network
Traceback (most recent call last):
  File "object_detection_demo_yolov4_async.py", line 521, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov4_async.py", line 323, in main
    net = ie.read_network(args.model, os.path.splitext(args.model)[0] + ".bin")
  File "ie_api.pyx", line 261, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 285, in openvino.inference_engine.ie_api.IECore.read_network
ValueError: invalid stoi argument

**Comment by TNTWEN** [comment]
What's your OpenVINO version？
And could you show me the command when you run object_detection_demo_yolov4_async.py？

**Comment by TNTWEN** [comment]
It seems that you use the wrong model file's path
`-m   .xml`

**Comment by 17695996717** [comment]
> It seems that you use the wrong model file's path
> `-m .xml`
First of all, I really appreciate your reply

my openvivo version is w_openvino_toolkit_p_2021.2.185.exe!
my run command is "python object_detection_demo_yolov4_async.py -i cam -m frozen_darknet_yolov4_model.xml  -d CPU"


i describe my all operation first.
env:windows tf1.15
1.i run convert_weights_pb.py with my custom weight.
2.i run master brance openvino-master to run mo.py
my yolov4.json is:
[
  {
    "id": "TFYOLOV3",
    "match_kind": "general",
    "custom_attributes": {
      "classes": 5,
      "anchors": [15, 36,  30, 45,  19, 82,  33,106,  65, 81,  33,227,  27,515, 204, 82,  86,244],
      "coords": 4,
      "num": 9,
      "masks":[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
      "entry_points": ["detector/yolo-v4/Reshape", "detector/yolo-v4/Reshape_4", "detector/yolo-v4/Reshape_8"]
    }
  }
]
3.finally,i run "python object_detection_demo_yolov4_async.py -i cam -m frozen_darknet_yolov4_model.xml  -d CPU"
but get the that error information
which version should i change? Looking forward to your reply!

**Comment by TNTWEN** [comment]
First ,you should use this demo:https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.2

And according to the error information:
net = ie.read_network(args.model, os.path.splitext(args.model)[0] + ".bin")

It just fail to find frozen_darknet_yolov4_model.xml  and frozen_darknet_yolov4_model.bin.Make sure you set true IRmodel path!

**Comment by 17695996717** [comment]
> First ,you should use this demo:https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.2
> 
> And according to the error information:
> net = ie.read_network(args.model, os.path.splitext(args.model)[0] + ".bin")
> 
> It just fail to find frozen_darknet_yolov4_model.xml and frozen_darknet_yolov4_model.bin.Make sure you set true IRmodel path!

thanks~
the demo :https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.2 used ngraph module only in linux,so i must install 2020.4 openvino in windows,i will try again.

**Comment by TNTWEN** [comment]
??
I have tested :https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.2 on windows

Obviously！Windows supports ngraph
![image](https://user-images.githubusercontent.com/49018311/111026929-1624c980-8428-11eb-8cbd-d00088264a36.png)

net = ie.read_network(args.model, os.path.splitext(args.model)[0] + ".bin")   is just an error loading the model

And you could try C++ demo C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\demos\multi_channel\object_detection_demo_yolov3

**Comment by TNTWEN** [comment]
Use right IRmodel path！
![image](https://user-images.githubusercontent.com/49018311/111027177-81bb6680-8429-11eb-8069-912c7c457f77.png)
![image](https://user-images.githubusercontent.com/49018311/111027180-8aac3800-8429-11eb-8306-c4ce89ba9b14.png)

**Comment by 17695996717** [comment]
> Use right IRmodel path！
> ![image](https://user-images.githubusercontent.com/49018311/111027177-81bb6680-8429-11eb-8069-912c7c457f77.png)
> ![image](https://user-images.githubusercontent.com/49018311/111027180-8aac3800-8429-11eb-8306-c4ce89ba9b14.png)

thanks for your reply,according your method ,i seem to solved some problem! and get right result in show  picture.
the first issue maybe use a bad xml and bin file! i generate xml and bin again by "C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\model_optimizer/mo.py" rather than in the github openvino-master version:openvino-master\model-optimizer/mo.py".it can work now,hope it can help others.

but there have some other problem

1.can i use my virtual env?i run it in my virtual env ,but i don't get the output of my env python version, my env python version is python=3.6.2. although it can work...!
![image](https://user-images.githubusercontent.com/55191031/111028418-7bc98380-8431-11eb-9b84-1062ff266fe9.png)
but if i don't activate my virtual ,it it will output python version
![image](https://user-images.githubusercontent.com/55191031/111028800-0b703180-8434-11eb-9bb3-87de24894471.png)
2.it too slow when i use the gpu:
python object_detection_demo_yolov3_async.py -i ./img/3.jpg -m frozen_darknet_yolov4_model.xml  -d GPU
I waited for a long time before the result show, and it seem don't use the gpu,my device is 1660ti,cuda 10.0,cudnn 7.6.5
and when i use the -i cam command,it only show the first frame pisture,such as:
![image](https://user-images.githubusercontent.com/55191031/111029496-d5cd4780-8437-11eb-9714-55b1034cc565.png)
![image](https://user-images.githubusercontent.com/55191031/111029497-d8c83800-8437-11eb-884e-3d4b508b644c.png)

do you know want possible problem?
Thanks again for your reply!

**Comment by TNTWEN** [comment]
`it only show the first frame pisture
`
https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/master/pythondemo/2021.2
download it again. I have solved it 2 hours ago.

Openvino GPU is Intel's GPU ,not Nvidia GPU,like this：
![image](https://user-images.githubusercontent.com/49018311/111029674-e5995b80-8438-11eb-9883-21bc9b0658d9.png)
 
GPU need FP16 IRmodel.
If  you want to use yolov4 +intel GPU+FP16  Please use OpenVINO2020.4 . (Details:https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/10  POINT 11)
If you want to use yolov4-tiny/yolov4-tiny-3l+intel GPU+FP16 .Any OpenVINO version(after2020.4) is OK.

**Comment by TNTWEN** [comment]
For faster yolov4 ,you could try:https://github.com/TNTWEN/Pruned-OpenVINO-YOLO

Pruned yolov4: 
The weight file is pruned from 245M to less than 1M
![image](https://user-images.githubusercontent.com/49018311/111030127-a28cb780-843b-11eb-8e2b-3c029cf8795e.png)

Runnning on I5 8250U CPU  11FPS:
![image](https://user-images.githubusercontent.com/49018311/111030077-6194a300-843b-11eb-90e5-1d6a2ae3ec0d.png)

Very awesome！！
Welcome to have a try!You can star this repos and it will continue to be updated

**Comment by 17695996717** [comment]
> For faster yolov4 ,you could try:https://github.com/TNTWEN/Pruned-OpenVINO-YOLO
> 
> Pruned yolov4:
> The weight file is pruned from 245M to less than 1M
> ![image](https://user-images.githubusercontent.com/49018311/111030127-a28cb780-843b-11eb-8e2b-3c029cf8795e.png)
> 
> Runnning on I5 8250U CPU 11FPS:
> ![image](https://user-images.githubusercontent.com/49018311/111030077-6194a300-843b-11eb-90e5-1d6a2ae3ec0d.png)
> 
> Very awesome！！
> Welcome to have a try!You can star this repos and it will continue to be updated

I have read it a few days ago~,i may be try it after i run object_detection_demo_yolov3_async.py in windows succeseful.
i'm try run object_detection_demo_yolov3_async.py in pycharm,but the ngraph module is occur error.
![image](https://user-images.githubusercontent.com/55191031/111032910-93146b00-8449-11eb-96e4-82b6305824f6.png)
i have copy openvino python ngraph and openvino module into my own env site-packge.
![image](https://user-images.githubusercontent.com/55191031/111033005-0f0eb300-844a-11eb-874b-e113d0c0b45d.png)
![image](https://user-images.githubusercontent.com/55191031/111033040-45e4c900-844a-11eb-8d40-8d832840e169.png)
i set these environment variables
![image](https://user-images.githubusercontent.com/55191031/111033103-880e0a80-844a-11eb-8451-274c15b596bf.png)
what should i do to import ngraph in pycharm successful!thanks

**Comment by TNTWEN** [comment]
There is no need to do so at all. 
Even in pycharm，you can run the program on the terminal.It is already enough.
I have developed many other applications based on openvino demo before.Terminal can completely meet my demand under Win and Ubuntu

**Comment by 17695996717** [comment]
the -i cam parameter still seem to be some problem. when i close current show-img window, it was able detect next frame img.

**Comment by TNTWEN** [comment]
In the development process, we usually install multiple versions at the same time.We can flexibly switch between multiple versions in the terminal.Every update OpenVINO adds many new packages,So there is no need to change the environment that openvino has packaged.It's just a waste of time.
![image](https://user-images.githubusercontent.com/49018311/111033676-5e0a1780-844d-11eb-8536-903bd25820a2.png)

**Comment by TNTWEN** [comment]
> the -i cam parameter still seem to be some problem. when i close current show-img window, it was able detect next frame img.

You never use opencv before? 
This is how opencv realizes video display
You can't exit the program by clicking the close button
Python demo has already told you how to exit the program
![image](https://user-images.githubusercontent.com/49018311/111033891-3ebfba00-844e-11eb-81e4-976e1d336e66.png)

**Comment by 17695996717** [comment]
> In the development process, we usually install multiple versions at the same time.We can flexibly switch between multiple versions in the terminal.Every update OpenVINO adds many new packages,So there is no need to change the environment that openvino has packaged.It's just a waste of time.
> ![image](https://user-images.githubusercontent.com/49018311/111033676-5e0a1780-844d-11eb-8536-903bd25820a2.png)

thank you, i get it!

**Comment by 17695996717** [comment]
> > the -i cam parameter still seem to be some problem. when i close current show-img window, it was able detect next frame img.
> 
> You never use opencv before?
> This is how opencv realizes video display
> You can't exit the program by clicking the close button
> Python demo has already told you how to exit the program
> ![image](https://user-images.githubusercontent.com/49018311/111033891-3ebfba00-844e-11eb-81e4-976e1d336e66.png)

Sorry, maybe I didn't express myself clearly~ What I mean is that it detect next frame by press tab?rather than detect next img with cam video streaming?

**Comment by TNTWEN** [comment]
> > > the -i cam parameter still seem to be some problem. when i close current show-img window, it was able detect next frame img.
> > 
> > 
> > You never use opencv before?
> > This is how opencv realizes video display
> > You can't exit the program by clicking the close button
> > Python demo has already told you how to exit the program
> > ![image](https://user-images.githubusercontent.com/49018311/111033891-3ebfba00-844e-11eb-81e4-976e1d336e66.png)
> 
> Sorry, maybe I didn't express myself clearly~ What I mean is that it detect next frame by press tab?rather than detect next img with cam video streaming?

You can simply understand it as the asynchronous mode of openvino video processing
While processing the previous frame, prepare for the next one. Instead of waiting for the previous frame to be processed completely before reading the next frame. This helps to reduce latency and improve FPS performance

**Comment by 17695996717** [comment]
> > > > the -i cam parameter still seem to be some problem. when i close current show-img window, it was able detect next frame img.
> > > 
> > > 
> > > You never use opencv before?
> > > This is how opencv realizes video display
> > > You can't exit the program by clicking the close button
> > > Python demo has already told you how to exit the program
> > > ![image](https://user-images.githubusercontent.com/49018311/111033891-3ebfba00-844e-11eb-81e4-976e1d336e66.png)
> > 
> > 
> > Sorry, maybe I didn't express myself clearly~ What I mean is that it detect next frame by press tab?rather than detect next img with cam video streaming?
> 
> You can simply understand it as the asynchronous mode of openvino video processing
> While processing the previous frame, prepare for the next one. Instead of waiting for the previous frame to be processed completely before reading the next frame. This helps to reduce latency and improve FPS performance

ok,Thank you very much for your professional answer!
