### ISSUE TITLE
Couldn't show result and save result when inputting an image

### ISSUE THREAD

**Issue by noeltong** [TNTWEN/OpenVINO-YOLOV4#41]
when the inference process is over, the result cannot be saved under the project directory.
but when i use the `-r` option, the output shows where the box is.
![Screenshot from 2021-04-04 11-05-57](https://user-images.githubusercontent.com/46706611/113533137-c2a93400-95ff-11eb-87b6-4b61e9f1348c.png)
can i save the result as a picture?

**Comment by TNTWEN** [comment]
![image](https://user-images.githubusercontent.com/49018311/113533393-672b7600-9600-11eb-978d-bf7a7cc02dee.png)

Add this line here
