### ISSUE TITLE
how to use multiple NCS2？

### ISSUE THREAD

**Issue by razgzy** [TNTWEN/OpenVINO-YOLOV4#49]
i want to use 2 NCS2 in 2021.3/....py, but can only use one with -d MYRIAD
i wonder where should be modified in code?

**Comment by TNTWEN** [comment]
@everfate 
Sorry,i don't have more than one NCS2 to test the code.
I think you could open an issue on Openvino Community to ask  OpenVINO engineers for help.

**Comment by razgzy** [comment]
> @everfate
> Sorry,i don't have more than one NCS2 to test the code.
> I think you could open an issue on Openvino Community to ask OpenVINO engineers for help.

thank you. i've found solution.
https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Multiple-NSC2-working-together-on-an-inference/m-p/1217030#M21022
