### ISSUE TITLE
请问作者有没有支持yolov5的计划？

### ISSUE THREAD

**Issue by OpenCDR** [TNTWEN/OpenVINO-YOLOV4#52]
如题，我直接套用您的量化json是没有办法量化yolov5s的。

**Comment by TNTWEN** [comment]
yolov5基本的模型转换与推理可以参考https://github.com/Chen-MingChang/pytorch_YOLO_OpenVINO_demo
但是scaledyolov4与yolov5都无法实现量化，这是受到了openvino量化工具的限制，该量化工具内置的是基本的yolov3模型，只能拓展至yolov4,v4tiny,v4tiny-3l。  scaledyolov4与yolov5的yolo层都无法与量化工具内置的yolov3 的yololayer模块兼容

**Comment by OpenCDR** [comment]
好的谢谢您，我训练一个v4tiny-3l实验下吧。但是官方文档里说yolov5的配置和v3一致就好，还挺奇怪的。
