### ISSUE TITLE
The running of openvino+HDDL-R8 is  slower than i3

### ISSUE THREAD

**Issue by lijunnankman** [TNTWEN/OpenVINO-YOLOV4#6]
I am Kman.When i use the HDDL-R8 accelerator card to run the official demo.The fps are very low,and it showed a very low "util%". My hardware configuration is as follows:

CPU: i3-8145UE
Vision Accelerator Card: hddl-R8
OS: Ubuntu18.04
OpenVINO:2020.4

Have you met this situation?

**Comment by TNTWEN** [comment]
Hello!
You could see my detailed test of AI-BoxX Gen.1(https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/5)
GPU is faster than HDDL-R8.AndI if you need to run other programs at the same time, I don't recommend that you use the CPU to do inference.
Thanks for your trying！

**Comment by TNTWEN** [comment]
In this project,GPU - Intel UHD Graphics 620 (WHL GT2)>HDDL-R8>CPU - Intel Core i3-8145UE CPU @ 2.20GHz × 4   if you run YOLOv4 correctly.
Until now ,i haven't test old YOLOV3 using intel AI-BoxX Gen.1.

**Comment by lijunnankman** [comment]
@TNTWEN Thank you for your reply. I agree with your recommention.However, when I run the intel demo(face_recognition_demo) in HDDL-R8,the fps is slower than i3. When I check the HDDL-r8's util% ,they are all less than 10%. Btw, my intel AI-BoxX Gen.1. is from Uzel.
