### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal, but are 40 and 30. Shapes are [?,40,30] and [?,30,40]

### ISSUE THREAD

**Issue by zgq91** [TNTWEN/OpenVINO-YOLOV4#7]
Hi:
  When the image width and height are not equal,  for example 640*480  "ValueError: Dimension 1 in both shapes must be equal, but are 40 and 30. Shapes are [?,40,30] and [?,30,40]"

**Comment by TNTWEN** [comment]
Hi!
Since OpenVINO YOLOV3,we usually set the height and width equal. Actually we usually resize pictures first when training.At present, this project also defaults to the same width and height.In the future, I will also try to support different widths and heights.
Thanks!

**Comment by TNTWEN** [comment]
Hi, @zgq91 
please let me know where you changed the code.
https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/eb9996c569cd80b34af8e51339e5f3169fa904ea/convert_weights_pb.py#L38        here?
Thanks!

**Comment by TNTWEN** [comment]
Hi, @zgq91 
I have fixed it .Please git clone and try again.  And let me know if it works!
if you want to use 640*480 remember to change this line https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/ab8b6454e3f59044095ba8914c5c36e09360ba08/convert_weights_pb.py#L38

to  `inputs = tf.placeholder(tf.float32, [None, 640, 480, 3], "inputs")`
Thanks for your trying!

**Comment by zgq91** [comment]
change the yolo_v4.py file  "   if data_format == 'NCHW':
        new_height = out_shape[2]
        new_width = out_shape[3]
        #new_height = out_shape[3]
        #new_width = out_shape[2]
    else:
        new_height = out_shape[1]
        new_width = out_shape[2]
        #new_height = out_shape[2]
        #new_width = out_shape[1]"  to work
